Console.WriteLine("Имя: Дима");
Console.WriteLine("Фамилия: Шевелёв");
Console.WriteLine("Отчество: Алексеевич");
Console.WriteLine("Учебное заведение: ITstep");
Console.WriteLine("Группа: П26");
Console.WriteLine("Возраст: 16");
Console.WriteLine("Год рождения: 2007");
Console.WriteLine("Год обучения: 3");
Console.WriteLine("Работа: нет");
Console.WriteLine("Хобби: готовка");